/* eslint-disable */
// Generated by Wrangler by running `wrangler types --config=wrangler.reader.jsonc --include-runtime=false --env-interface=ReaderEnv reader/env.d.ts` (hash: 58bf061d61e8195e7bad64aedd179870)
interface __BaseEnv_ReaderEnv {
  READING_LIMIT: RateLimit;
  AI: Ai;
  READER_TOKEN: string;
}
declare namespace Cloudflare {
  interface GlobalProps {
    mainModule: typeof import("./index");
  }
  interface Env extends __BaseEnv_ReaderEnv {}
}
interface ReaderEnv extends __BaseEnv_ReaderEnv {}
type StringifyValues<EnvType extends Record<string, unknown>> = {
  [Binding in keyof EnvType]: EnvType[Binding] extends string
    ? EnvType[Binding]
    : string;
};
declare namespace NodeJS {
  interface ProcessEnv extends StringifyValues<
    Pick<Cloudflare.Env, "READER_TOKEN">
  > {}
}
