/* eslint-disable */
// Generated by Wrangler by running `wrangler types --include-runtime=false worker/env.d.ts` (hash: cffb21e53bcd95751b733950352d1d74)
interface __BaseEnv_Env {
	ASSETS: Fetcher;
	CONVEX_HTTP_URL: "https://beaming-ferret-793.convex.site";
}
declare namespace Cloudflare {
	interface GlobalProps {
		mainModule: typeof import("./index");
	}
	interface Env extends __BaseEnv_Env {}
}
interface Env extends __BaseEnv_Env {}
type StringifyValues<EnvType extends Record<string, unknown>> = {
	[Binding in keyof EnvType]: EnvType[Binding] extends string ? EnvType[Binding] : string;
};
declare namespace NodeJS {
	interface ProcessEnv extends StringifyValues<Pick<Cloudflare.Env, "CONVEX_HTTP_URL">> {}
}
